"""
Specifies the kind of information a job should be able to provide
"""
# pylint: disable=missing-class-docstring,missing-function-docstring

from typing import Protocol

class Job(Protocol):

    def name(self) -> str: ...

    def complete(self) -> bool: ...

    def pending(self) -> bool: ...

    def running(self) -> bool: ...

    def blocked(self) -> bool: ...

    def ready(self) -> bool: ...

    def failed(self) -> bool: ...

    def run(self, force: bool = False) -> None: ...

    def cancel(self) -> None: ...

    def setup(self) -> None: ...

    def in_progress(self) -> bool: ...
