"""
Specifies the kind of information a job should be able to provide
"""
# pylint: disable=missing-class-docstring,missing-function-docstring

from typing import Protocol
from .environment import Environment

class Job(Protocol):

    def name(self) -> str: ...

    def complete(self) -> bool: ...

    def failed(self, env: Environment) -> bool: ...

    def blocked(self) -> bool: ...

    def ready(self) -> bool: ...

    def setup(self) -> None: ...

    def reset(self) -> None: ...

    def command(self) -> str: ...
